# havaintopaikkojen lataus ja koordinaattimuunnos

### koordinaatit, paikka_Id, KuntaNimi

In [1]:
import pandas as pd

data = pd.DataFrame()

df = pd.read_json("http://rajapinnat.ymparisto.fi/api/Hydrologiarajapinta/1.0/odata/Virtaama?$top=392&$filter=year(Aika)%20eq%202019%20and%20Paikka/Tila_Id%20eq%201&$expand=Paikka")
data = data.append(df)

In [2]:
data.drop("odata.metadata",1,inplace=True)

In [3]:
data

                                                 value
0    {'Paikka': {'Paikka_Id': 894, 'Suure_Id': 2, '...
1    {'Paikka': {'Paikka_Id': 895, 'Suure_Id': 2, '...
2    {'Paikka': {'Paikka_Id': 896, 'Suure_Id': 2, '...
3    {'Paikka': {'Paikka_Id': 897, 'Suure_Id': 2, '...
4    {'Paikka': {'Paikka_Id': 898, 'Suure_Id': 2, '...
5    {'Paikka': {'Paikka_Id': 900, 'Suure_Id': 2, '...
6    {'Paikka': {'Paikka_Id': 901, 'Suure_Id': 2, '...
7    {'Paikka': {'Paikka_Id': 903, 'Suure_Id': 2, '...
8    {'Paikka': {'Paikka_Id': 905, 'Suure_Id': 2, '...
9    {'Paikka': {'Paikka_Id': 907, 'Suure_Id': 2, '...
10   {'Paikka': {'Paikka_Id': 908, 'Suure_Id': 2, '...
11   {'Paikka': {'Paikka_Id': 909, 'Suure_Id': 2, '...
12   {'Paikka': {'Paikka_Id': 910, 'Suure_Id': 2, '...
13   {'Paikka': {'Paikka_Id': 917, 'Suure_Id': 2, '...
14   {'Paikka': {'Paikka_Id': 919, 'Suure_Id': 2, '...
15   {'Paikka': {'Paikka_Id': 921, 'Suure_Id': 2, '...
16   {'Paikka': {'Paikka_Id': 923, 'Suure_Id': 2, '...
17   {'Paikka': {'Paikka_Id': 924, 'Suure_Id': 2, '...
18   {'Paikka': {'Paikka_Id': 927, 'Suure_Id': 2, '...
19   {'Paikka': {'Paikka_Id': 931, 'Suure_Id': 2, '...
20   {'Paikka': {'Paikka_Id': 935, 'Suure_Id': 2, '...
21   {'Paikka': {'Paikka_Id': 937, 'Suure_Id': 2, '...
22   {'Paikka': {'Paikka_Id': 938, 'Suure_Id': 2, '...
23   {'Paikka': {'Paikka_Id': 939, 'Suure_Id': 2, '...
24   {'Paikka': {'Paikka_Id': 941, 'Suure_Id': 2, '...
25   {'Paikka': {'Paikka_Id': 943, 'Suure_Id': 2, '...
26   {'Paikka': {'Paikka_Id': 944, 'Suure_Id': 2, '...
27   {'Paikka': {'Paikka_Id': 946, 'Suure_Id': 2, '...
28   {'Paikka': {'Paikka_Id': 949, 'Suure_Id': 2, '...
29   {'Paikka': {'Paikka_Id': 951, 'Suure_Id': 2, '...
..                                                 ...
362  {'Paikka': {'Paikka_Id': 3328, 'Suure_Id': 2, ...
363  {'Paikka': {'Paikka_Id': 3329, 'Suure_Id': 2, ...
364  {'Paikka': {'Paikka_Id': 3330, 'Suure_Id': 2, ...
365  {'Paikka': {'Paikka_Id': 3334, 'Suure_Id': 2, ...
366  {'Paikka': {'Paikka_Id': 3335, 'Suure_Id': 2, ...
367  {'Paikka': {'Paikka_Id': 3394, 'Suure_Id': 2, ...
368  {'Paikka': {'Paikka_Id': 3406, 'Suure_Id': 2, ...
369  {'Paikka': {'Paikka_Id': 3499, 'Suure_Id': 2, ...
370  {'Paikka': {'Paikka_Id': 3524, 'Suure_Id': 2, ...
371  {'Paikka': {'Paikka_Id': 3532, 'Suure_Id': 2, ...
372  {'Paikka': {'Paikka_Id': 3536, 'Suure_Id': 2, ...
373  {'Paikka': {'Paikka_Id': 3538, 'Suure_Id': 2, ...
374  {'Paikka': {'Paikka_Id': 3540, 'Suure_Id': 2, ...
375  {'Paikka': {'Paikka_Id': 3542, 'Suure_Id': 2, ...
376  {'Paikka': {'Paikka_Id': 3544, 'Suure_Id': 2, ...
377  {'Paikka': {'Paikka_Id': 3551, 'Suure_Id': 2, ...
378  {'Paikka': {'Paikka_Id': 3558, 'Suure_Id': 2, ...
379  {'Paikka': {'Paikka_Id': 3568, 'Suure_Id': 2, ...
380  {'Paikka': {'Paikka_Id': 3581, 'Suure_Id': 2, ...
381  {'Paikka': {'Paikka_Id': 3602, 'Suure_Id': 2, ...
382  {'Paikka': {'Paikka_Id': 3607, 'Suure_Id': 2, ...
383  {'Paikka': {'Paikka_Id': 3619, 'Suure_Id': 2, ...
384  {'Paikka': {'Paikka_Id': 3674, 'Suure_Id': 2, ...
385  {'Paikka': {'Paikka_Id': 3678, 'Suure_Id': 2, ...
386  {'Paikka': {'Paikka_Id': 3681, 'Suure_Id': 2, ...
387  {'Paikka': {'Paikka_Id': 3682, 'Suure_Id': 2, ...
388  {'Paikka': {'Paikka_Id': 3683, 'Suure_Id': 2, ...
389  {'Paikka': {'Paikka_Id': 3719, 'Suure_Id': 2, ...
390  {'Paikka': {'Paikka_Id': 3727, 'Suure_Id': 2, ...
391  {'Paikka': {'Paikka_Id': 3728, 'Suure_Id': 2, ...

[392 rows x 1 columns]

In [4]:
data2 = pd.DataFrame.from_dict({(i,j): data[i][j] 
                           for i in data.keys() 
                           for j in data[i].keys()},
                       orient='index')

In [5]:
data2.reset_index(drop=True, inplace=True)

In [6]:
data2.head()

,Paikka,Paikka_Id,Aika,Arvo,ArvoMin,ArvoMax,Lippu_id,huomautus
0,"{'Paikka_Id': 894, 'Suure_Id': 2, 'H_Kunta_Id'...",894,2019-01-01T00:00:00,8.20,None,None,NaN,None
1,"{'Paikka_Id': 895, 'Suure_Id': 2, 'H_Kunta_Id'...",895,2019-01-01T00:00:00,9.80,None,None,NaN,None
2,"{'Paikka_Id': 896, 'Suure_Id': 2, 'H_Kunta_Id'...",896,2019-01-01T00:00:00,1.96,None,None,NaN,None
3,"{'Paikka_Id': 897, 'Suure_Id': 2, 'H_Kunta_Id'...",897,2019-01-01T00:00:00,2.52,None,None,NaN,None
4,"{'Paikka_Id': 898, 'Suure_Id': 2, 'H_Kunta_Id'...",898,2019-01-01T00:00:00,5.26,None,None,NaN,None

In [7]:
paikka_data = data2["Paikka"].to_dict()

In [8]:
paikka_data = pd.DataFrame.from_dict(paikka_data, orient = "index")

In [9]:
paikka_data

,Paikka_Id,Suure_Id,H_Kunta_Id,KuntaNimi,Nro,Nimi,KoordYkPohj,KoordYkIta,KoordPkPohj,KoordPkIta,...,Laitteisto_Id,H_Vesal_Id,VesalNimi,H_PaaVesal_Id,PaaVesalNimi,KoordErTmPohj,KoordErTmIta,Jarvi_Id,JarviNro,JarviNimi
0,894,2,167,Joensuu,0100150,Ruskeakoski,6929395,3677929,6924731,4522990,...,9.0,10,Loitimon la,1,None,6926492,677686,93.0,01.021.1.001,Melakko-Loitimo
1,895,2,848,Tohmajärvi,0101251,Vääräkoski,6905869,3682250,6901039,4526215,...,9.0,4,Jänisjoen keskiosan a,1,None,6902976,682005,18.0,01.011.1.018,Varislampi
2,896,2,260,Kitee,0201000,Kontturi,6879031,3674209,6874612,4516944,...,7.0,69,Kiteenjoen alaosan a,2,None,6876149,673968,742.0,02.021.1.001,Kamarahkonlampi
3,897,2,689,Rautjärvi,0300250,Juankoski,6816330,3625189,6814253,4465100,...,9.0,81,Simpelejärven alaosan la,3,None,6813473,624968,835.0,03.012.1.020,Konkanlampi
4,898,2,689,Rautjärvi,0300450,Kangaskoski,6813860,3628467,6811636,4468260,...,9.0,78,Kokkolanjoen a,3,None,6811004,628245,813.0,03.011.1.001,Lahnanen
5,900,2,422,Lieksa,0400520,"Jongunjoki, Viitakoski",7054821,3649961,7051283,4500911,...,7.0,340,Jongunjoen a,4,None,7051867,649728,NaN,None,None
6,901,2,422,Lieksa,0400600,"Lieksanjoki, Ruunaa",7039784,3673459,7035167,4523671,...,7.0,389,Ruunaanjärven a,4,None,7036836,673217,8332.0,04.492.1.001,Polvijärvi
7,903,2,422,Lieksa,0400850,"Lieksanjoki, Lieksankoski",7029531,3652258,7025920,4502020,...,9.0,332,Lieksankosken a,4,None,7026588,652025,6961.0,04.421.1.003,Riikolanlampi
8,905,2,541,Nurmes,0401110,"Saramojoki, Roukkajankoski",7062005,3603895,7060618,4455241,...,7.0,370,Roukkajankosken a,4,None,7059048,603681,7860.0,04.471.1.001,Ylikylänjärvi
9,907,2,911,Valtimo,0401320,"Valtimonjoki, Nuolikoski",7068677,3587060,7068072,4438739,...,7.0,362,Nuolijärven a,4,None,7065717,586853,NaN,None,None
10,908,2,541,Nurmes,0401350,"Valtimonjoki, Kuokkastenkoski",7050388,3597388,7049319,4448197,...,9.0,360,Valtimonjoen alaosan a,4,None,7047436,597177,6579.0,04.411.1.001,Pielinen
11,909,2,146,Ilomantsi,0401920,"Haapajoki, Putkulankoski",7005765,3703577,6999792,4552153,...,7.0,650,Haapajoen a,4,None,7002832,703323,NaN,None,None
12,910,2,146,Ilomantsi,0402120,"Koitajoki, Möhkönkoski",6956124,3720558,6949439,4566795,...,7.0,632,Möhkön a,4,None,6953211,720297,NaN,None,None
13,917,2,167,Joensuu,0402850,"Koitajoki, Pamilo",6970992,3675052,6966401,4522051,...,9.0,6190,Pamilon - Palojärven a,4,None,6968072,674810,11066.0,04.912.1.001,Palojärvi
14,919,2,167,Joensuu,0403350,"Pielisjoki, Kaltimo",6966746,3660018,6962860,4506840,...,9.0,6167,Kaltimon - Uimaharjun a,4,None,6963828,659782,6046.0,04.341.1.001,Alusvesi
15,921,2,276,Kontiolahti,0404350,"Pielisjoki, Kuurna",6958903,3647285,6955621,4493760,...,9.0,6166,Kuurnan - Jakokosken a,4,None,6955988,647054,NaN,None,None
16,923,2,607,Polvijärvi,0404813,Rauanjoki,6983341,3624227,6981100,4471870,...,7.0,596,Rauanjoen alaosan a,4,None,6980416,624005,NaN,None,None
17,924,2,276,Kontiolahti,0404850,"Höytiäinen, Puntarikoski",6955641,3635942,6952890,4482280,...,9.0,589,Höytiäisen la,4,None,6952727,635716,NaN,None,None
18,927,2,260,Kitee,0405250,"Pyhäjärvi, Puhos",6890994,3650369,6887660,4493690,...,9.0,311,Pyhäjärven a,4,None,6888107,650137,5802.0,04.311.1.001,Orivesi (Saimaa N60+75.80)
19,931,2,925,Vieremä,0405750,"Salahminjärvi, Salahmi",7078060,3496874,7078060,3496874,...,9.0,426,Salahminjärven la,4,None,7075096,496703,8683.0,04.541.1.001,Salahminjärvi
20,935,2,140,Iisalmi,0406260,"Porovesi, Nerohvirta",7040680,3511288,7040680,3511288,...,9.0,398,Nerkoonjärven a,4,None,7037731,511112,8479.0,04.512.1.001,Nerkoonjärvi
21,937,2,297,Kuopio,0406460,"Onkivesi, Viannonkoski",7013100,3510400,7013100,3510400,...,9.0,397,Onkiveden la,4,None,7010162,510224,8439.0,04.511.1.001,Onkivesi
22,938,2,297,Kuopio,0406610,Pulkonkoski,7002919,3509000,7002919,3509000,...,7.0,243,Ala-Pulkon va,4,None,6999985,508825,5669.0,04.287.1.001,Ala-Pulkko
23,939,2,762,Sonkajärvi,0406750,"Laakajärvi, Kiltua",7081520,3544230,7081520,3544230,...,9.0,502,Laakajärven a,4,None,7078555,544040,9705.0,04.644.1.001,Laakajärvi
24,941,2,762,Sonkajärvi,0406860,"Kiltuanjärvi, Jyrkkä",7075410,3540050,7075410,3540050,...,9.0,501,Kiltuanjärven a,4,None,7072447,539862,9679.0,04.642.1.040,Haapajärvi
25,943,2,402,Lapinlahti,0406950,Sälevä,7046156,3547383,7046156,3547383,...,9.0,6180,Sälevän - Nurmijoen a,4,None,7043205,547192,NaN,None,None
26,944,2,402,Lapinlahti,0407050,Atro,7030450,3549600,7030450,3549600,...,9.0,500,Korpisen a,4,None,7027506,549408,9626.0,04.641.1.001,Karsanjärvi
27,946,2,297,Kuopio,0407260,"Syväri, Lastukoski",7011984,3564360,7011984,3564360,...,9.0,490,Syvärin la,4,None,7009047,564162,9325.0,04.621.1.001,Vuotjärvi
28,949,2,297,Kuopio,0407410,Keyritty - luusua,7030546,3568968,7030546,3568968,...,7.0,522,Keyrityn a,4,None,7027602,568768,9964.0,04.672.1.002,Valkeislampi
29,951,2,297,Kuopio,0407750,Karjalankoski,6994200,3566180,6994200,3566180,...,9.0,471,Karjalankosken a,4,None,6991270,565982,9187.0,04.611.1.070,Heikinlampi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
362,3328,2,420,Leppävirta,0418081,Konnuskoski,6938546,3539703,6938546,3539703,...,8.0,231,Kallaveden a,4,None,6935639,539516,NaN,None,None
363,3329,2,420,Leppävirta,0428081,Naapuskoski,6938198,3542135,6938198,3542135,...,7.0,231,Kallaveden a,4,None,6935291,541947,4829.0,04.272.1.001,Kallavesi (N60 81.70)
364,3330,2,420,Leppävirta,0438081,Konnus laivakanava,6938397,3539958,6938397,3539958,...,7.0,231,Kallaveden a,4,None,6935490,539771,4829.0,04.272.1.001,Kallavesi (N60 81.70)
365,3334,2,261,Kittilä,6500710,Pallasjärvi-luusua,7551523,3386743,7549065,2512040,...,7.0,4416,Pallasjärven va,65,None,7548370,386616,NaN,None,None
366,3335,2,261,Kittilä,6500720,Pyhäjoki,7551476,3380852,7548732,2506159,...,7.0,4416,Pallasjärven va,65,None,7548323,380728,NaN,None,None
367,3394,2,261,Kittilä,6503221,Seurujoki,7538967,3430897,7538667,2556747,...,7.0,4454,Seurujoen va,65,None,7535819,430753,NaN,None,None
368,3406,2,927,Vihti,2300402,Olkkalanjoki,6706704,3354459,6703835,2519589,...,7.0,1482,Olkkalanjoen a,23,None,6703889,354349,NaN,None,None
369,3499,2,10,Alavus,4200420,Seinäjärvi,6924834,3311619,6919691,2466785,...,9.0,2431,Sulkveenjoen va,42,None,6921931,311524,NaN,None,None
370,3524,2,149,Inkoo,8103200,Ingarskilaån,6664790,3344877,6661540,2511924,...,7.0,5634,Ingarskila ån va,81,None,6661992,344771,NaN,None,None
371,3532,2,905,Vaasa,4200900,Hiirikoski,6998701,3254547,6989962,1558342,...,9.0,2385,Tervajoen yläosan va,42,None,6995767,254475,NaN,None,None
372,3536,2,408,Lapua,4409110,"Hourunkoski, kokonaisvirtaama",6988978,3304376,6983402,2456570,...,9.0,2482,Lapuan a,44,None,6986049,304284,NaN,None,None
373,3538,2,408,Lapua,4403200,"Mäkelänkoski, kokonaisvirtaama",6983828,3311017,6978569,2463441,...,9.0,2484,Seuruksen a,44,None,6980901,310922,NaN,None,None
374,3540,2,989,Ähtäri,3543100,"Ryötönkoski, kokonaisvirtaama",6937796,3351591,6934490,2506098,...,9.0,1874,Oulunveden a,35,None,6934888,351480,NaN,None,None
375,3542,2,989,Ähtäri,3542400,"Vääräkoski, kokonaisvirtaama",6938893,3347939,6935416,2502400,...,9.0,1867,Peränteen a,35,None,6935984,347830,NaN,None,None
376,3544,2,139,Ii,6300101,Kivijoki,7288259,3455346,7288259,3455346,...,7.0,3967,Kivijoen suualue,63,None,7285211,455191,NaN,None,None
377,3551,2,301,Kurikka,4200432,Liikapuron tekojärvi pato,6924223,3297482,6918426,2452698,...,7.0,2435,Liikaluoman va,42,None,6921320,297393,NaN,None,None
378,3558,2,599,Pedersören kunta,4700350,Hattar,7058200,3307960,7052685,2456913,...,9.0,2582,Värnumin a,47,None,7055243,307866,NaN,None,None
379,3568,2,301,Kurikka,4200290,"Jalasjoki, Jalasjärvi",6939594,3280866,6933002,2435395,...,7.0,2408,Jalasjärven a,42,None,6936684,280784,NaN,None,None
380,3581,2,75,Hamina,1300101,"Reitkalli, Puutarhak. silta",6723312,3505676,6723312,3505676,...,7.0,723,Summajoen alaosan a,13,None,6720492,505504,NaN,None,None
381,3602,2,171,Joroinen,0409760,Liuna,6896530,3541490,6896530,3541490,...,9.0,6154,Välijoen - Sysmäjärven a,4,None,6893640,541303,4297.0,04.251.1.004,Jokijärvi
382,3607,2,52,Evijärvi,4700430,"Evijärvi, Kaarenhaara",7041890,3320386,7036982,2470085,...,9.0,2584,Kattilakosken a,47,None,7038939,320287,25261.0,47.021.1.001,Evijärvi
383,3619,2,153,Imatra,0411760,"Vuoksi, Imatra",6785940,3595810,6785248,4434360,...,9.0,109,Vuoksen a,4,None,6783095,595601,NaN,None,None
384,3674,2,420,Leppävirta,0448081,Konnus tulvakanava,6938465,3539768,6938465,3539768,...,9.0,231,Kallaveden a,4,None,6935558,539581,4829.0,04.272.1.001,Kallavesi (N60 81.70)
385,3678,2,853,Turku,2801000,Paattistenjoki mittapato,6722933,3244721,6714659,1573963,...,7.0,1585,Paattistenjoen va,28,None,6720111,244655,NaN,None,None
386,3681,2,405,Lappeenranta,0600200,Kalliokoskenoja,6768076,3567361,6768076,3567361,...,9.0,681,Rakkolanjoen yläosan va,6,None,6765238,567164,NaN,None,None
387,3682,2,405,Lappeenranta,0600800,Haapajärvi,6756089,3570936,6756089,3570936,...,9.0,681,Rakkolanjoen yläosan va,6,None,6753256,570738,NaN,None,None
388,3683,2,405,Lappeenranta,0600210,Lisävesi Rakkolanjokeen,6772653,3570336,6772653,3570336,...,9.0,681,Rakkolanjoen yläosan va,6,None,6769813,570138,NaN,None,None
389,3719,2,734,Salo,2400000,Perniönjoki Pohjankoski,6694120,3286425,6688174,2452224,...,7.0,1508,Perniönjoen keskiosan a,24,None,6691310,286342,NaN,None,None
390,3727,2,683,Ranua,6502130,Näskänjärvi,7345461,3489992,7345461,3489992,...,9.0,4169,Piittisjoen va,65,None,7342390,489823,NaN,None,None
391,3728,2,698,Rovaniemi,6502140,Paattinkijärvi,7349303,3481253,7349303,3481253,...,9.0,4169,Piittisjoen va,65,None,7346230,481088,NaN,None,None

In [10]:
paikka_data.columns

Index(['Paikka_Id', 'Suure_Id', 'H_Kunta_Id', 'KuntaNimi', 'Nro', 'Nimi',
       'KoordYkPohj', 'KoordYkIta', 'KoordPkPohj', 'KoordPkIta', 'KoordLat',
       'KoordLong', 'KoordTarkkuus', 'Karttalehti', 'Omistaja_Id', 'Tila_Id',
       'Laitteisto_Id', 'H_Vesal_Id', 'VesalNimi', 'H_PaaVesal_Id',
       'PaaVesalNimi', 'KoordErTmPohj', 'KoordErTmIta', 'Jarvi_Id', 'JarviNro',
       'JarviNimi'],
      dtype='object')

In [11]:
paikka_data.drop(["Suure_Id", "Nro", "KoordYkPohj", 'KoordYkIta', 'KoordPkPohj', 'KoordPkIta', 'KoordLat',
       'KoordLong', 'KoordTarkkuus', 'Karttalehti', 'Omistaja_Id', 'Tila_Id',
       'Laitteisto_Id', 'H_Vesal_Id', 'VesalNimi', 'H_PaaVesal_Id',
       'PaaVesalNimi', "Jarvi_Id", "JarviNro", "JarviNimi", "H_Kunta_Id"],1, inplace=True)

In [12]:
paikka_data

,Paikka_Id,KuntaNimi,Nimi,KoordErTmPohj,KoordErTmIta
0,894,Joensuu,Ruskeakoski,6926492,677686
1,895,Tohmajärvi,Vääräkoski,6902976,682005
2,896,Kitee,Kontturi,6876149,673968
3,897,Rautjärvi,Juankoski,6813473,624968
4,898,Rautjärvi,Kangaskoski,6811004,628245
5,900,Lieksa,"Jongunjoki, Viitakoski",7051867,649728
6,901,Lieksa,"Lieksanjoki, Ruunaa",7036836,673217
7,903,Lieksa,"Lieksanjoki, Lieksankoski",7026588,652025
8,905,Nurmes,"Saramojoki, Roukkajankoski",7059048,603681
9,907,Valtimo,"Valtimonjoki, Nuolikoski",7065717,586853
10,908,Nurmes,"Valtimonjoki, Kuokkastenkoski",7047436,597177
11,909,Ilomantsi,"Haapajoki, Putkulankoski",7002832,703323
12,910,Ilomantsi,"Koitajoki, Möhkönkoski",6953211,720297
13,917,Joensuu,"Koitajoki, Pamilo",6968072,674810
14,919,Joensuu,"Pielisjoki, Kaltimo",6963828,659782
15,921,Kontiolahti,"Pielisjoki, Kuurna",6955988,647054
16,923,Polvijärvi,Rauanjoki,6980416,624005
17,924,Kontiolahti,"Höytiäinen, Puntarikoski",6952727,635716
18,927,Kitee,"Pyhäjärvi, Puhos",6888107,650137
19,931,Vieremä,"Salahminjärvi, Salahmi",7075096,496703
20,935,Iisalmi,"Porovesi, Nerohvirta",7037731,511112
21,937,Kuopio,"Onkivesi, Viannonkoski",7010162,510224
22,938,Kuopio,Pulkonkoski,6999985,508825
23,939,Sonkajärvi,"Laakajärvi, Kiltua",7078555,544040
24,941,Sonkajärvi,"Kiltuanjärvi, Jyrkkä",7072447,539862
25,943,Lapinlahti,Sälevä,7043205,547192
26,944,Lapinlahti,Atro,7027506,549408
27,946,Kuopio,"Syväri, Lastukoski",7009047,564162
28,949,Kuopio,Keyritty - luusua,7027602,568768
29,951,Kuopio,Karjalankoski,6991270,565982
...,...,...,...,...,...
362,3328,Leppävirta,Konnuskoski,6935639,539516
363,3329,Leppävirta,Naapuskoski,6935291,541947
364,3330,Leppävirta,Konnus laivakanava,6935490,539771
365,3334,Kittilä,Pallasjärvi-luusua,7548370,386616
366,3335,Kittilä,Pyhäjoki,7548323,380728
367,3394,Kittilä,Seurujoki,7535819,430753
368,3406,Vihti,Olkkalanjoki,6703889,354349
369,3499,Alavus,Seinäjärvi,6921931,311524
370,3524,Inkoo,Ingarskilaån,6661992,344771
371,3532,Vaasa,Hiirikoski,6995767,254475
372,3536,Lapua,"Hourunkoski, kokonaisvirtaama",6986049,304284
373,3538,Lapua,"Mäkelänkoski, kokonaisvirtaama",6980901,310922
374,3540,Ähtäri,"Ryötönkoski, kokonaisvirtaama",6934888,351480
375,3542,Ähtäri,"Vääräkoski, kokonaisvirtaama",6935984,347830
376,3544,Ii,Kivijoki,7285211,455191
377,3551,Kurikka,Liikapuron tekojärvi pato,6921320,297393
378,3558,Pedersören kunta,Hattar,7055243,307866
379,3568,Kurikka,"Jalasjoki, Jalasjärvi",6936684,280784
380,3581,Hamina,"Reitkalli, Puutarhak. silta",6720492,505504
381,3602,Joroinen,Liuna,6893640,541303
382,3607,Evijärvi,"Evijärvi, Kaarenhaara",7038939,320287
383,3619,Imatra,"Vuoksi, Imatra",6783095,595601
384,3674,Leppävirta,Konnus tulvakanava,6935558,539581
385,3678,Turku,Paattistenjoki mittapato,6720111,244655
386,3681,Lappeenranta,Kalliokoskenoja,6765238,567164
387,3682,Lappeenranta,Haapajärvi,6753256,570738
388,3683,Lappeenranta,Lisävesi Rakkolanjokeen,6769813,570138
389,3719,Salo,Perniönjoki Pohjankoski,6691310,286342
390,3727,Ranua,Näskänjärvi,7342390,489823
391,3728,Rovaniemi,Paattinkijärvi,7346230,481088

In [13]:
# KoordErTm == epsg:3067

from pyproj import Proj, transform

inProj = Proj(init='epsg:3067')
outProj = Proj(init='epsg:4326')
x1,y1 = paikka_data["KoordErTmIta"].tolist(), paikka_data["KoordErTmPohj"].tolist()
x2,y2 = transform(inProj,outProj,x1,y1)

In [14]:
paikka_data["lat"] = y2

In [15]:
paikka_data["lon"] = x2

In [16]:
#paikka_data.to_csv("virtaama_mittauspaikat.csv", index = None)

# havaintojen lataus

In [38]:
import pandas as pd
import requests


paska = pd.DataFrame()

for i in paikka_data.KuntaNimi.unique():
    r = requests.get("http://rajapinnat.ymparisto.fi/api/Hydrologiarajapinta/1.0/odata/Virtaama?$filter=year(Aika)%20eq%202019%20and%20Paikka/Tila_Id%20eq%201%20and%20Paikka/KuntaNimi%20eq%20%27{0}%27".format(i)).json()
    df = pd.DataFrame.from_dict(r)
    paska = paska.append(df, sort = True)

In [40]:
paska.head()

,odata.metadata,odata.nextLink,value
0,http://rajapinnat.ymparisto.fi/api/Hydrologiar...,NaN,"{'Paikka_Id': 894, 'Aika': '2019-01-01T00:00:0..."
1,http://rajapinnat.ymparisto.fi/api/Hydrologiar...,NaN,"{'Paikka_Id': 917, 'Aika': '2019-01-01T00:00:0..."
2,http://rajapinnat.ymparisto.fi/api/Hydrologiar...,NaN,"{'Paikka_Id': 919, 'Aika': '2019-01-01T00:00:0..."
3,http://rajapinnat.ymparisto.fi/api/Hydrologiar...,NaN,"{'Paikka_Id': 894, 'Aika': '2019-01-02T00:00:0..."
4,http://rajapinnat.ymparisto.fi/api/Hydrologiar...,NaN,"{'Paikka_Id': 917, 'Aika': '2019-01-02T00:00:0..."

In [41]:
paska.drop(["odata.metadata","odata.nextLink"],1,inplace=True)

In [42]:
paska.reset_index(inplace=True, drop=True)

In [47]:
paska.shape

(39515, 1)

In [48]:
kakka = paska.iloc[0:39514].to_dict()
data2 = pd.DataFrame.from_dict({(i,j): kakka[i][j] 
                            for i in kakka.keys() 
                            for j in kakka[i].keys()},
                        orient='index')

In [50]:
data2.head()

         Paikka_Id                 Aika    Arvo ArvoMin ArvoMax  Lippu_id  \
value 0        894  2019-01-01T00:00:00    8.20    None    None       NaN
      1        917  2019-01-01T00:00:00    4.46    None    None       NaN
      2        919  2019-01-01T00:00:00  171.98    None    None       NaN
      3        894  2019-01-02T00:00:00    8.20    None    None       NaN
      4        917  2019-01-02T00:00:00    4.40    None    None       NaN

        huomautus
value 0      None
      1      None
      2      None
      3      None
      4      None

In [51]:
data2.reset_index(drop=True, inplace=True)

In [52]:
data2.drop(["ArvoMin", "ArvoMax", "Lippu_id", "huomautus"],1,inplace=True)

In [54]:
merge = pd.merge(paikka_data, data2)

In [56]:
merge.head()

,Paikka_Id,KuntaNimi,Nimi,KoordErTmPohj,KoordErTmIta,lat,lon,Aika,Arvo
0,894,Joensuu,Ruskeakoski,6926492,677686,62.427083,30.441868,2019-01-01T00:00:00,8.20
1,894,Joensuu,Ruskeakoski,6926492,677686,62.427083,30.441868,2019-01-02T00:00:00,8.20
2,894,Joensuu,Ruskeakoski,6926492,677686,62.427083,30.441868,2019-01-03T00:00:00,8.20
3,894,Joensuu,Ruskeakoski,6926492,677686,62.427083,30.441868,2019-01-04T00:00:00,8.20
4,894,Joensuu,Ruskeakoski,6926492,677686,62.427083,30.441868,2019-01-05T00:00:00,8.20

In [57]:
merge.Aika = pd.to_datetime(merge.Aika)

In [58]:
merge.sort_values(by=["Aika"], inplace=True)

In [59]:
merge.reset_index(inplace=True, drop=True)

In [60]:
merge

,Paikka_Id,KuntaNimi,Nimi,KoordErTmPohj,KoordErTmIta,lat,lon,Aika,Arvo
0,894,Joensuu,Ruskeakoski,6926492,677686,62.427083,30.441868,2019-01-01,8.20
1,1057,Kouvola,Piirteenvirta,6725815,491394,60.667965,26.842524,2019-01-01,146.00
2,3328,Leppävirta,Konnuskoski,6935639,539516,62.549558,27.768337,2019-01-01,66.60
3,2739,Sodankylä,Matarakoski,7496647,489232,67.585254,26.746944,2019-01-01,59.13
4,1365,Rovaniemi,Pirttikoski,7357823,506945,66.340055,27.155087,2019-01-01,272.51
5,1136,Hämeenlinna,Kukkia - luusua,6795324,376915,61.272688,24.704231,2019-01-01,2.00
6,1237,Lestijärvi,Lestijärvi - luusua,7052637,386689,63.583599,24.716922,2019-01-01,1.58
7,1021,Jyväskylä,Saarijärvi - luusua,6873774,414760,61.986763,25.373161,2019-01-01,0.17
8,1277,Suomussalmi,Palojärvi - luusua,7183054,635055,64.744933,29.837680,2019-01-01,1.64
9,1056,Kouvola,Kuusankoski,6752516,480938,60.907326,26.648582,2019-01-01,143.31
10,955,Leppävirta,Kallavesi - Konnus + Karvio,6935678,539528,62.549906,27.768580,2019-01-01,111.10
11,1364,Kemijärvi,Seitakorva,7372976,515721,66.475673,27.352968,2019-01-01,256.79
12,1137,Valkeakoski,Valkeakoski,6795818,340601,61.263979,24.027440,2019-01-01,12.00
13,1360,Pelkosenniemi,Kemihaara,7453727,533970,67.198533,27.785513,2019-01-01,59.95
14,1213,Seinäjoki,"Kyrönjoki, Hanhikoski",6988348,282529,62.959636,22.710180,2019-01-01,3.38
15,954,Leppävirta,"Kallavesi, Konnus",6935678,539528,62.549906,27.768580,2019-01-01,68.10
16,956,Kaavi,Saarijärvi - luusua,6978951,583939,62.930740,28.653371,2019-01-01,4.79
17,1235,Kokkola,Hyyppä,7086643,325504,63.863337,23.448400,2019-01-01,0.47
18,1134,Padasjoki,Vesijako - Sumperinvirta,6807152,396056,61.384380,25.054412,2019-01-01,0.35
19,901,Lieksa,"Lieksanjoki, Ruunaa",7036836,673217,63.417815,30.470659,2019-01-01,47.00
20,3682,Lappeenranta,Haapajärvi,6753256,570738,60.908111,28.304178,2019-01-01,0.74
21,1373,Enontekiö,Ounasjärvi - luusua,7590545,366612,68.396119,23.752423,2019-01-01,2.03
22,1127,Eurajoki,Pappilankoski,6796713,218261,61.202987,21.753470,2019-01-01,4.09
23,1060,Kouvola,Piirteenvirta,6722898,486696,60.641647,26.756756,2019-01-01,135.13
24,1239,Kannus,Saarenpää,7099504,341537,63.986205,23.760789,2019-01-01,3.07
25,1372,Rovaniemi,"Olkkajärvi, Permantokoski",7375116,461143,66.492834,26.126963,2019-01-01,9.38
26,1131,Orivesi,Äväntäjärvi - luusua,6847935,376217,61.744379,24.655956,2019-01-01,0.35
27,1276,Suomussalmi,Vuokkijärvi - luusua,7189309,600650,64.813087,29.119884,2019-01-01,8.85
28,958,Juuka,Kajoonjärvi - luusua,7003924,595687,63.151857,28.899162,2019-01-01,0.97
29,1058,Kouvola,Anjala,6729206,490034,60.698379,26.817465,2019-01-01,134.00
...,...,...,...,...,...,...,...,...,...
39081,1373,Enontekiö,Ounasjärvi - luusua,7590545,366612,68.396119,23.752423,2019-04-25,3.59
39082,1230,Kruunupyy,Kruunupyy,7072447,302935,63.724260,23.008349,2019-04-25,22.20
39083,1237,Lestijärvi,Lestijärvi - luusua,7052637,386689,63.583599,24.716922,2019-04-25,3.50
39084,1123,Pöytyä,Yläneenjoki,6757295,250905,60.872382,22.410257,2019-04-25,0.91
39085,1374,Kittilä,"Ounasjoki, Köngäs",7530912,409428,67.878636,24.844374,2019-04-25,128.88
39086,1122,Eurajoki,Ylinenkoski,6793668,213399,61.172241,21.668001,2019-04-25,2.81
39087,3678,Turku,Paattistenjoki mittapato,6720111,244655,60.535675,22.344015,2019-04-25,0.34
39088,1133,Padasjoki,Vesijako - Palsankoski,6804242,392011,61.357168,24.980438,2019-04-25,0.68
39089,1223,Alajärvi,Kurejoki,6989266,338946,62.997244,23.819757,2019-04-25,19.80
39090,1008,Konnevesi,Konnevesi - luusua,6942164,465119,62.608587,26.320440,2019-04-26,42.50
39091,1397,Pello,Pello,7410802,364232,66.785234,23.912405,2019-04-26,668.00
39092,1005,Rautalampi,"Niinivesi, Nokisenkoski",6953488,493851,62.711825,26.879788,2019-04-26,27.00
39093,976,Virolahti,Salmen silta,6720617,534595,60.619895,27.632099,2019-04-26,16.87
39094,1106,Lohja,Väänteenjoki,6692396,338072,60.335651,24.066490,2019-04-26,7.57
39095,977,Pihtipudas,Saanijärvi - luusua,7029076,428846,63.383203,25.576475,2019-04-26,16.55
39096,980,Viitasaari,"Kärnäjärvi, Kellankoski",7003466,446269,63.156443,25.933477,2019-04-26,11.71
39097,963,Heinävesi,Kermajärvi - luusua,6919511,590583,62.395884,28.752367,2019-04-26,70.90
39098,1252,Ylivieska,Hamari,7107681,381936,64.075590,24.579219,2019-04-26,0.00
39099,1087,Hyvinkää,Kytäjärvi - luusua,6721639,372564,60.610306,24.671949,2019-04-26,2.66
39100,1021,Jyväskylä,Saarijärvi - luusua,6873774,414760,61.986763,25.373161,2019-04-26,4.34
39101,3260,Nokia,"Siuro, ylä",6821428,304736,61.477142,23.333269,2019-04-26,61.00
39102,1250,Ylivieska,Padinki,7098997,390796,64.000626,24.766947,2019-04-26,61.03
39103,1070,Pyhtää,Hirvikoski,6719831,480609,60.613862,26.645768,2019-04-26,109.60
39104,1347,Ranua,Hosionkoski,7311286,446946,65.918209,25.834741,2019-04-26,84.80
39105,1158,Ruovesi,Muroleenkoski,6861798,337460,61.854153,23.910670,2019-04-26,54.60
39106,1330,Puolanka,Suolijärvi - luusua,7224989,550136,65.144550,28.069000,2019-04-26,107.20
39107,1186,Kokemäki,Sääksjärvi - luusua,6813703,257691,61.381437,22.462874,2019-04-26,13.64
39108,1022,Petäjävesi,Petäjävesi - luusua,6898342,405559,62.205005,25.184528,2019-04-26,39.20
39109,1085,Hyvinkää,Ylä-Suolijärvi - luusua,6723087,371759,60.623039,24.656315,2019-04-26,0.80
39110,1123,Pöytyä,Yläneenjoki,6757295,250905,60.872382,22.410257,2019-04-26,0.80

In [61]:
#merge.to_csv("virtaama.csv", index=None)

In [35]:
import pandas as pd
import requests

paikka_data = pd.read_csv("virtaama.csv")

def update(havainto, kuntanimi, vuosi):
    paska = pd.DataFrame()
    r = requests.get("http://rajapinnat.ymparisto.fi/api/Hydrologiarajapinta/1.0/odata/{0}?$filter=Paikka/Tila_Id%20eq%201%20and%20Paikka/KuntaNimi%20eq%20%27{1}%27%20and%20year(Aika)%20eq%20{2}".format(havainto, kuntanimi, vuosi)).json()
    df = pd.DataFrame.from_dict(r)
    paska = paska.append(df, sort = True)
    
    r2 = requests.get("http://rajapinnat.ymparisto.fi/api/Hydrologiarajapinta/1.0/odata/{0}?$filter=Paikka/Tila_Id%20eq%201%20and%20Paikka/KuntaNimi%20eq%20%27{1}%27%20and%20year(Aika)%20eq%20{2}&$skip=500".format(havainto, kuntanimi, vuosi)).json()
    df2 = pd.DataFrame.from_dict(r2)
    paska = paska.append(df2, sort = True)
    
    r3 = requests.get("http://rajapinnat.ymparisto.fi/api/Hydrologiarajapinta/1.0/odata/{0}?$filter=Paikka/Tila_Id%20eq%201%20and%20Paikka/KuntaNimi%20eq%20%27{1}%27%20and%20year(Aika)%20eq%20{2}&$skip=1000".format(havainto, kuntanimi, vuosi)).json()
    df3 = pd.DataFrame.from_dict(r3)
    paska = paska.append(df3, sort = True)
    
    if "odata.metadata" and "odata.nextLink" in paska.columns:
        paska.drop(["odata.metadata", "odata.nextLink"],1, inplace = True)
    else:
        paska.drop(["odata.metadata"],1,inplace = True)
    
    paska.reset_index(inplace=True, drop=True)
    
    df2 = pd.DataFrame.from_dict({(i,j): paska[i][j] 
                            for i in paska.keys() 
                            for j in paska[i].keys()},
                        orient='index')
    
    df2.reset_index(inplace=True, drop=True)
    df2.drop(["ArvoMin", "ArvoMax", "Lippu_id", "huomautus"],1,inplace=True)
    df2.Aika = pd.to_datetime(df2.Aika)
    df2.to_csv("virtaama_mittaukset.csv", index = None, mode = "a", header = None)

In [36]:
for i in paikka_data.KuntaNimi.unique():
    update("Virtaama", i, 2019)

In [44]:

#merged = pd.merge(df, paikka_data.drop(["Arvo", "Aika", "KoordErTmPohj", "KoordErTmIta", "lat", "lon"],1))

       894  2019-01-01    8.20  Unnamed: 3
0      917  2019-01-01    4.46         NaN
1      919  2019-01-01  171.98         NaN
2      894  2019-01-02    8.20         NaN
3      917  2019-01-02    4.40         NaN
4      919  2019-01-02  171.98         NaN
5      894  2019-01-03    8.20         NaN
6      917  2019-01-03   56.24         NaN
7      919  2019-01-03  168.18         NaN
8      894  2019-01-04    8.20         NaN
9      917  2019-01-04   61.38         NaN
10     919  2019-01-04  166.22         NaN
11     894  2019-01-05    8.20         NaN
12     917  2019-01-05   22.80         NaN
13     919  2019-01-05  165.98         NaN
14     894  2019-01-06    8.20         NaN
15     917  2019-01-06    4.40         NaN
16     919  2019-01-06  164.43         NaN
17     894  2019-01-07    8.20         NaN
18     917  2019-01-07    5.81         NaN
19     919  2019-01-07  163.98         NaN
20     894  2019-01-08    8.20         NaN
21     917  2019-01-08   33.75         NaN
22     919  2019-01-08  163.98         NaN
23     894  2019-01-09    8.20         NaN
24     917  2019-01-09   94.48         NaN
25     919  2019-01-09  166.18         NaN
26     894  2019-01-10    8.20         NaN
27     917  2019-01-10   86.18         NaN
28     919  2019-01-10  166.99         NaN
29     894  2019-01-11    8.20         NaN
...    ...         ...     ...         ...
46698  917  2019-04-19   50.10         NaN
46699  919  2019-04-19  159.64         NaN
46700  894  2019-04-20   22.01         NaN
46701  917  2019-04-20    6.73         NaN
46702  919  2019-04-20  163.95         NaN
46703  894  2019-04-21   26.39         NaN
46704  917  2019-04-21    6.59         NaN
46705  919  2019-04-21  167.19         NaN
46706  894  2019-04-22   29.82         NaN
46707  917  2019-04-22    6.51         NaN
46708  919  2019-04-22  171.20         NaN
46709  894  2019-04-23   34.23         NaN
46710  917  2019-04-23   20.60         NaN
46711  919  2019-04-23  171.98         NaN
46712  894  2019-04-24   39.00         NaN
46713  917  2019-04-24   93.39         NaN
46714  919  2019-04-24  175.03         NaN
46715  894  2019-04-25   45.76         NaN
46716  917  2019-04-25  139.15         NaN
46717  919  2019-04-25  179.74         NaN
46718  894  2019-04-26   55.99         NaN
46719  917  2019-04-26  151.68         NaN
46720  919  2019-04-26  186.98         NaN
46721  894  2019-04-27   63.42         NaN
46722  917  2019-04-27   95.56         NaN
46723  919  2019-04-27  193.84         NaN
46724  894  2019-04-28   71.07         NaN
46725  917  2019-04-28   65.22         NaN
46726  919  2019-04-28  203.51         NaN
46727  917  2019-04-29  141.91         NaN

[46728 rows x 4 columns]

In [54]:
#merged.to_csv("vedenpinnankorkeus.csv", index = None)

In [13]:
import pandas as pd

df = pd.read_csv("virtaama_mittaukset.csv", index_col = False, names = ["Paikka_Id", "Aika", "Arvo"])
df2 = pd.read_csv("virtaama.csv")
df2.columns

Index(['Paikka_Id', 'KuntaNimi', 'Nimi', 'KoordErTmPohj', 'KoordErTmIta',
       'lat', 'lon', 'Aika', 'Arvo'],
      dtype='object')

In [15]:
merged = pd.merge(df,df2.drop(["KoordErTmPohj", "KoordErTmIta", "lat", "lon", "Aika", "Arvo"],1), on = "Paikka_Id")

In [17]:
merged.drop_duplicates(inplace=True)

In [19]:
merged.reset_index(inplace=True, drop=True)

In [11]:
import datetime

x = datetime.datetime.now()
print("{0}-{1}-{2}".format(x.year, x.month, x.day))

2019-4-30

In [17]:
("http://rajapinnat.ymparisto.fi/api/Hydrologiarajapinta/1.0/odata/{0}?$top=100&$filter=Paikka/KuntaNimi%20eq%20%27{1}%27%20and%20Paikka/Tila_Id%20eq%201%20and%20year(Aika)%20eq%20{2}%20and%20month(Aika)%20eq%20{3}%20and%20day(Aika)%20eq%20{4}".format(havainto, kuntanimi, x.year, x.month, x.day))

'http://rajapinnat.ymparisto.fi/api/Hydrologiarajapinta/1.0/odata/Virtaama?$top=100&$filter=Paikka/KuntaNimi%20eq%20%27Joensuu%27%20and%20Paikka/Tila_Id%20eq%201%20and%20year(Aika)%20eq%202019%20and%20month(Aika)%20eq%204%20and%20day(Aika)%20eq%2030'

In [1]:
#today
import datetime
import pandas as pd
import requests
def update_data(havainto, kuntanimi):
    df = pd.DataFrame()
    x = datetime.datetime.now()
    r = requests.get("http://rajapinnat.ymparisto.fi/api/Hydrologiarajapinta/1.0/odata/{0}?$top=100&$filter=Paikka/KuntaNimi%20eq%20%27{1}%27%20and%20Paikka/Tila_Id%20eq%201%20and%20year(Aika)%20eq%20{2}%20and%20month(Aika)%20eq%20{3}%20and%20day(Aika)%20eq%20{4}".format(havainto, kuntanimi, x.year, x.month, x.day)).json()
    df_from_dict = pd.DataFrame.from_dict(r)
    df = df.append(df_from_dict)
    
    if "odata.metadata" and "odata.nextLink" in df.columns:
        df.drop(["odata.metadata", "odata.nextLink"],1, inplace = True)
    else:
        df.drop(["odata.metadata"],1,inplace = True)
        
    df.reset_index(inplace=True, drop=True)
    
    df2 = pd.DataFrame.from_dict({(i,j): df[i][j] 
                            for i in df.keys() 
                            for j in df[i].keys()},
                        orient='index')
    
    df2.reset_index(inplace=True, drop=True)
    if "ArvoMin" and "ArvoMax" and "Lippu_id" and "huomautus" in df2.columns:
        df2.drop(["ArvoMin", "ArvoMax", "Lippu_id", "huomautus"],1,inplace=True)
        df2.Aika = pd.to_datetime(df2.Aika)
    if "ArvoMin" and "ArvoMax" and "Lippu_id" in df2.columns:
        df2.drop(["ArvoMin", "ArvoMax", "Lippu_id"],1,inplace=True)
        df2.Aika = pd.to_datetime(df2.Aika)
    else:
        pass
    #df2.to_csv("{0}_mittaukset_update.csv".format(havainto), index = None, mode = "a", header = None)
    print(df2)

In [75]:
vesi = pd.read_csv("vedenpinnankorkeus.csv")

for i in vesi.KuntaNimi.unique():
    update_data("Vedenkorkeus", i)